# @package _global_

defaults: 
  - override /hydra/launcher: submitit_slurm
  - _self_

hydra: 
  launcher: 
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 480 # 8 hours
    cpus_per_task: 16
    mem_gb: 32
    name: ${hydra.job.name}
    stderr_to_stdout: false
    qos: m2
    comment: null
    gres: gpu:a40:1
    signal_delay_s: 120
    max_num_timeout: 5
    setup: 
      - export TQDM_MININTERVAL=30
    additional_parameters:
        error: /dev/null  
        output: /dev/null
        begin: now+60

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback